version: '3.8'

services:
  app:
    image: 'commission-microservice:latest'
    build:
      context: .
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/turnover
      - SPRING_DATASOURCE_USERNAME=username
      - SPRING_DATASOURCE_PASSWORD=password
    ports:
      - "8080:8080"